---
- name: Configure nginx
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Wait for system to be ready
      raw: test -e /var/lib/dpkg/lock-frontend || true
      retries: 10
      delay: 5

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy index.html
      copy:
        src: ../html/index.html
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Ensure nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes
